### ISSUE TITLE
Compilation warning "(re)run Biber on the file"

### ISSUE THREAD

**Issue by Zeyecx** [francois-rozet/sleek-template#1]
Hi, I have problems with your template. However, I find it so nice that I still want to use it. Can you help me how to fix the errors?
```shell
 pdflatex.exe -synctex=1 -interaction=nonstopmode "main.tex"
```

![image](https://user-images.githubusercontent.com/15014849/126074211-cf7456c5-c985-44ee-9367-bb0e3371d6de.png)

**Comment by Zeyecx** [comment]
I have compiled your project with Github Workflow. It doesn't work there either. I have attached the log for you. Can you help me there?

https://github.com/Zeyecx/LatexTemplate/runs/3097906076

**Comment by francois-rozet** [comment]
Hi @Zeyecx 👋 

That is in fact the expected warning for the **first** run. As explained by the message, you now have to run `biber` (to build the bibliography-related files) and then re-run LaTeX (in your case `pdflatex`).

Normally, you shouldn't have to do that manually as most LaTeX editors (texmaker, texstudio, overleaf, etc.) do it automatically. For more information, see

* https://tex.stackexchange.com/questions/523493/package-biblatex-warning-please-rerun-biber
* https://tex.stackexchange.com/questions/154751/biblatex-with-biber-configuring-my-editor-to-avoid-undefined-citations

**Comment by Zeyecx** [comment]
```shell
zeyecx@Lenovo:/mnt/c/git/sleek-template$ pdflatex -synctex=1 -interaction=nonstopmode main.tex
This is pdfTeX, Version 3.14159265-2.6-1.40.20 (TeX Live 2019/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./main.tex
LaTeX2e <2020-02-02> patch level 2
L3 programming layer <2020-02-14>
(/usr/share/texlive/texmf-dist/tex/latex/base/report.cls
Document Class: report 2019/12/20 v1.4l Standard LaTeX document class
(/usr/share/texlive/texmf-dist/tex/latex/base/size12.clo))
(/usr/share/texlive/texmf-dist/tex/generic/babel/babel.sty
(/usr/share/texlive/texmf-dist/tex/generic/babel/switch.def)
(/usr/share/texlive/texmf-dist/tex/generic/babel-english/english.ldf
(/usr/share/texlive/texmf-dist/tex/generic/babel/babel.def
(/usr/share/texlive/texmf-dist/tex/generic/babel/txtbabel.def))))
(./packages/sleek.sty

LaTeX Warning: You have requested package `packages/sleek',
               but the package provides `sleek'.

(/usr/share/texmf/tex/latex/lm/lmodern.sty)
(/usr/share/texlive/texmf-dist/tex/latex/base/fontenc.sty
(/usr/share/texmf/tex/latex/lm/t1lmr.fd))
(/usr/share/texlive/texmf-dist/tex/latex/base/inputenc.sty)

! LaTeX Error: File `eurosym.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name:
! Emergency stop.
<read *>

l.16 ^^M

!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on main.log.
zeyecx@Lenovo:/mnt/c/git/sleek-template$ biber main.tex
INFO - This is Biber 2.14 (beta)
INFO - Logfile is 'main.tex.blg'
ERROR - Cannot find 'main.tex.bcf'!
INFO - ERRORS: 1
```

**Comment by Zeyecx** [comment]
Unfortunately, the bibier only crashes. I throw out a few parts and put the packages in the root. Maybe that will help.

**Comment by francois-rozet** [comment]
You should call `biber main` not `biber main.tex`.
