### ISSUE TITLE
Language options in sleek-theorems have no effect

### ISSUE THREAD

**Issue by JanB1** [francois-rozet/sleek-template#4]
Hello there, I was able to resolve my last issue. But not I stumbled upon a new issue.
I implemented my own language option and tried to use it. I can't seem to be able to get it to work though.

How do you apply a different language to the theorems? I tried using the option "French", but I got "missing \begin{document}" in the "sleek-theorems" package.

**Comment by francois-rozet** [comment]
Hello @JanB1,

There is indeed a bug with the language options in `sleek-theorems`. The options are processed at the end of the file, which means they do not affect the defined environments ... I have fixed the bug in the last commit (c2b13eaa074552d32f61609a5ab2463a8412e432). Thanks for the feedback!

To create a new language option, you can copy the `french` option block and edit it for your language.

https://github.com/francois-rozet/sleek-template/blob/c2b13eaa074552d32f61609a5ab2463a8412e432/packages/sleek-theorems.sty#L41-L55

Don't forget to change the option name (e.g. `german`) and to activate it, with

```latex
\usepackage[german]{packages/sleek-theorems}
```

**Comment by francois-rozet** [comment]
I'll close the issue. If you still have issues, leave a comment.
